// app/layout.tsx

import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import ClientLayout from "./ClientLayout"; // ⚡ 클라이언트 로직을 담을 새 컴포넌트
import "./assets/css/main.css";
import "./assets/css/fontawesome-all.min.css";

// ⚡ Noto Sans 폰트를 next/font를 통해 가져옵니다.
const notoSans = Noto_Sans({
  subsets: ["latin"],
  weight: ["400", "600"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Html5up Editorial Next.js & TypeScript",
  description: "Generated by create next.js 로 마이그레이션",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={notoSans.className}>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
