// app/layout.tsx

import type { Metadata } from "next";
import Sidebar from "./components/Sidebar";
import "./assets/css/main.css"; 
import "./assets/css/fontawesome-all.min.css";

export const metadata: Metadata = {
  title: "Html5up Editorial Next.js & TypeScript",
  description: "Generated by create next.js 로 마이그레이션",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* 전체 페이지의 뼈대가 브라우저에 찍히는 곳 */}
        <div id="root">
          <div id="wrapper">
            <div id="main">
              <div className="inner">
                {children}
              </div>
            </div>
            <div id="sidebar">
              <Sidebar />
            </div>
          </div>
          </div>
      </body>
    </html>
  );
}
