// app/layout.tsx

"use client"; 
import { useState, useEffect } from "react"; // Changed from 'import type' to 'import'
import Sidebar from "./components/Sidebar";
import "./assets/css/main.css"; 
import "./assets/css/fontawesome-all.min.css";

// export const metadata: Metadata = {
//   title: "Html5up Editorial Next.js & TypeScript",
//   description: "Generated by create next.js 로 마이그레이션",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [isInactive, setIsInactive] = useState(false); // 1280px 이상에서 기본적으로 활성(보임) 상태로 시작
  const [isPreloaded, setIsPreloaded] = useState(true);

  useEffect(() => {
    const handleResize = () => {
      // 화면 너비가 1280px 이하이면 사이드바를 비활성화(숨김)
      if (window.innerWidth <= 1280) {
        setIsInactive(true);
      } else {
        // 1280px보다 크면 사이드바를 활성화
        setIsInactive(false);
      }
      // 화면 크기 계산 후 애니메이션 제한 해제
      setIsPreloaded(false);
    };

    // 컴포넌트 마운트 시 초기 실행
    handleResize();

    window.addEventListener("resize", handleResize);
    return () => window.removeEventListener("resize", handleResize);
  }, []);

  // 1280px 이하 환경에서 메인 영역 클릭 시 사이드바를 자동으로 닫는 함수
  const handleMainClick = () => {
    // 현재 사이드바가 열려있는 상태(!isInactive)이고 화면이 1280px 이하일 때만 닫음(true)
    if (!isInactive && window.innerWidth <= 1280) {
      setIsInactive(true);
    }
  };

  return (
    <html lang="en">
      <body className={isPreloaded ? "is-preload" : ""}>
        {/* 전체 페이지의 뼈대가 브라우저에 찍히는 곳 */}
        <div id="root">
          <div id="wrapper">
            <div id="main" onClick={handleMainClick}>
              <div className="inner">
                {children}
              </div>
            </div>
            <div id="sidebar" className={isInactive ? "inactive" : ""}>
              <Sidebar isInactive={isInactive} setIsInactive={setIsInactive} />
            </div>
          </div>
          </div>
      </body>
    </html>
  );
}
